### PR TITLE
Migrate to Sinatra. 

### LINKED ISSUE #2: Overlap with fork sign and output
screen shot 2015-10-27 at 6 54 30 pm</img>

That shouldn't happen should it :P

### PR DESCRIPTION
**Pull request by elifoster**
Remove drama counting because it doesnt work with the current setup, and I am unsure how to actually do it.

Hey @Strikingwolf do you wanna do a code review? :blue_heart: 

Fix #2

### CODE REVIEW

**Comment by elifoster** [comment]
I'm just gonna merge because it's pretty much the same code as before...

**Comment by Strikingwolf** [comment]
@houndci Single quoted is rubocop standard

**Comment by elifoster** [comment]
Yeah I reported that to them https://github.com/thoughtbot/hound/issues/977

**Comment by Strikingwolf** [comment]
Oh, didn't know that houndci was automated *facepalms*

**Pull request merged**
